"""API endpoints for managing intermediate artifacts."""

from datetime import datetime
from pathlib import Path

from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import FileResponse
from pydantic import BaseModel
from sqlalchemy.orm import Session

from src.database import get_db
from src.auth import CurrentUser, get_current_user
from src.services.conversation_service import ConversationService
from src.config import settings

router = APIRouter(prefix="/api/conversations/{conversation_id}/artifacts", tags=["artifacts"])


# ===== Response Models =====

class ArtifactItem(BaseModel):
    """Artifact file information."""
    filename: str
    size: int
    path: str  # Relative container path like /workspace/intermediate/filename
    created_at: datetime


# ===== Helper Functions =====

def get_artifact_directory(user_id: int, conversation_id: int) -> Path:
    """Get intermediate directory path for a user's conversation.
    
    Path: {base_dir}/intermediate/{user_id}/{conversation_id}
    """
    return settings.INTERMEDIATE_DIR / str(user_id) / str(conversation_id)


# ===== Endpoints =====

@router.get("", response_model=list[ArtifactItem])
async def list_artifacts(
    conversation_id: int,
    current_user: CurrentUser = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """
    List all intermediate files generated by the agent.
    """
    # Verify conversation access
    service = ConversationService(db)
    conversation = await service.get_conversation(conversation_id, current_user.id)
    if not conversation:
        raise HTTPException(status_code=404, detail="Conversation not found")

    artifact_dir = get_artifact_directory(current_user.id, conversation_id)
    
    if not artifact_dir.exists():
        return []

    files = []
    for file_path in artifact_dir.iterdir():
        if file_path.is_file():
            stat = file_path.stat()
            files.append(
                ArtifactItem(
                    filename=file_path.name,
                    size=stat.st_size,
                    path=f"/workspace/intermediate/{file_path.name}",
                    created_at=datetime.fromtimestamp(stat.st_ctime),
                )
            )
            
    # Sort by creation time (newest first)
    files.sort(key=lambda x: x.created_at, reverse=True)
    return files


@router.get("/{filename}")
async def download_artifact(
    conversation_id: int,
    filename: str,
    current_user: CurrentUser = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """
    Download a specific intermediate file.
    """
    # Verify conversation access
    service = ConversationService(db)
    conversation = await service.get_conversation(conversation_id, current_user.id)
    if not conversation:
        raise HTTPException(status_code=404, detail="Conversation not found")

    artifact_dir = get_artifact_directory(current_user.id, conversation_id)
    file_path = artifact_dir / filename

    # Security check: prevent directory traversal
    try:
        file_path.resolve().relative_to(artifact_dir.resolve())
    except ValueError:
        raise HTTPException(status_code=400, detail="Invalid filename")

    if not file_path.exists() or not file_path.is_file():
        raise HTTPException(status_code=404, detail="File not found")

    return FileResponse(
        path=file_path,
        filename=filename,
        media_type="application/octet-stream"
    )


@router.delete("/{filename}")
async def delete_artifact(
    conversation_id: int,
    filename: str,
    current_user: CurrentUser = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """
    Delete a specific intermediate file.
    """
    # Verify conversation access
    service = ConversationService(db)
    conversation = await service.get_conversation(conversation_id, current_user.id)
    if not conversation:
        raise HTTPException(status_code=404, detail="Conversation not found")

    artifact_dir = get_artifact_directory(current_user.id, conversation_id)
    file_path = artifact_dir / filename

    # Security check
    try:
        file_path.resolve().relative_to(artifact_dir.resolve())
    except ValueError:
        raise HTTPException(status_code=400, detail="Invalid filename")

    if not file_path.exists():
        raise HTTPException(status_code=404, detail="File not found")

    try:
        file_path.unlink()
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to delete file: {e}")

    return {"message": f"Artifact '{filename}' deleted successfully"}
